spring.application.name=demojpa
server.port=9090

# spring.datasource.url=jdbc:mysql://localhost:3306/company
# spring.datasource.username=tcetuser
# spring.datasource.password=tcet@123

pring.datasource.url=jdbc:mysql://72.60.219.201:3306/company
spring.datasource.username=ciauser
spring.datasource.password=C!auser@123$%

# Automatically create or update the database tables
spring.jpa.hibernate.ddl-auto=update